### PR TITLE
Fix the keybind not being registered

### PR DESCRIPTION
**Pull request by Mrbysco**

### CODE REVIEW

**Comment by Mrbysco** [comment]
This fixes #463

**Comment by Lothrazar** [comment]
looks amazing ill release this tonight

**Comment by zipszak** [comment]
How to eneable it? im not really good at this things

**Comment by HalcyonSeas73** [comment]
> How to eneable it? im not really good at this things

Update your Simple Storage Network mod

**Comment by zipszak** [comment]
but where i paste it

**Comment by zipszak** [comment]
i have the newest version of mod i dowlanded it 2 weeks ago

**Comment by HalcyonSeas73** [comment]
> i have the newest version of mod i dowlanded it 2 weeks ago

Are you asking where to put mods that you download? You're in the wrong section for learning how to use Minecraft mods. You've resurrected an old post asking about keybinds. If you have an issue with the mod itself, make a new GitHub issue. If you want to learn how to install the mod, Google is your friend.

**Comment by zipszak** [comment]
Im asking about where to put the text that is in first comment i know where to put mods i dodn't know how to chenge the keybind

**Comment by HalcyonSeas73** [comment]
> Im asking about where to put the text that is in first comment i know where to put mods i dodn't know how to chenge the keybind

There's a whole menu for it in Minecraft, under Options > Controls > Key binds...

You don't put the text in the first comment anywhere. This thread is on an old fix for an old issue. You apply it by updating the mod, which you've already done.

**Comment by zipszak** [comment]
But i still dont have the keybind option

**Pull request merged**
