### PR TITLE
more vanilla-ish texture for the man gui

### PR DESCRIPTION
**Pull request by Seegras**
Hi

I made a more vanilla-ish texture for the main gui. I actually would like the buttons and such also changed and more centered, but haven't found out how this works yet.

### CODE REVIEW

**Comment by PrinceOfAmber** [comment]
Hey! im still alive. ill check this out and see if i love it

**Comment by PrinceOfAmber** [comment]
Its cool, it looks ok.

Ill have to think on it.

Maybe we could put a button so users could pick the look they want, would be a bit of work ?

**Comment by Seegras** [comment]
I actually would like it to be even more vanilla-ish; with the buttons bigger and more centered (there is actually space for them now), but I don't yet know how this works.

**Comment by PrinceOfAmber** [comment]
My suggestion is to make a resource pack.  Soartex Fanver has custom textures for every thing inside of storage network  https://soartex.net/downloads/ and it looks great

For more information you can check https://www.twitch.tv/darkosto he used fanver, and has a discord with lots of helpful people.  I could be wrong but i think , artdude543

You can use any existing/modified textures on a curseforge texture pack no problem.

Since i am maintaining a fork of someone elses mod i want to keep the classic look and feel for everyone.

**Pull request closed without merging**
